// Code generated by "enumer -type=Mode"; DO NOT EDIT.

package veqryndedup

import (
	"fmt"
	"strings"
)

const _ModeName = "NoneOverIgnoreIncrGroup"

var _ModeIndex = [...]uint8{0, 4, 8, 14, 18, 23}

const _ModeLowerName = "noneoverignoreincrgroup"

func (i Mode) String() string {
	if i >= Mode(len(_ModeIndex)-1) {
		return fmt.Sprintf("Mode(%d)", i)
	}
	return _ModeName[_ModeIndex[i]:_ModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ModeNoOp() {
	var x [1]struct{}
	_ = x[None-(0)]
	_ = x[Over-(1)]
	_ = x[Ignore-(2)]
	_ = x[Incr-(3)]
	_ = x[Group-(4)]
}

var _ModeValues = []Mode{None, Over, Ignore, Incr, Group}

var _ModeNameToValueMap = map[string]Mode{
	_ModeName[0:4]:        None,
	_ModeLowerName[0:4]:   None,
	_ModeName[4:8]:        Over,
	_ModeLowerName[4:8]:   Over,
	_ModeName[8:14]:       Ignore,
	_ModeLowerName[8:14]:  Ignore,
	_ModeName[14:18]:      Incr,
	_ModeLowerName[14:18]: Incr,
	_ModeName[18:23]:      Group,
	_ModeLowerName[18:23]: Group,
}

var _ModeNames = []string{
	_ModeName[0:4],
	_ModeName[4:8],
	_ModeName[8:14],
	_ModeName[14:18],
	_ModeName[18:23],
}

// ModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ModeString(s string) (Mode, error) {
	if val, ok := _ModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mode values", s)
}

// ModeValues returns all values of the enum
func ModeValues() []Mode {
	return _ModeValues
}

// ModeStrings returns a slice of all String values of the enum
func ModeStrings() []string {
	strs := make([]string, len(_ModeNames))
	copy(strs, _ModeNames)
	return strs
}

// IsAMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mode) IsAMode() bool {
	for _, v := range _ModeValues {
		if i == v {
			return true
		}
	}
	return false
}
