package verify

import (
	"bytes"
	"context"
	"encoding/json"
	"log/slog"
	"math"

	"github.com/stretchr/testify/suite"

	testJSON "github.com/madkins23/go-slog/json"
	"github.com/madkins23/go-slog/test"
)

const (
	message = "This is a message"
)

// SlogTestSuite provides various tests for a specified log/slog.Hander.
type SlogTestSuite struct {
	suite.Suite
	*bytes.Buffer
}

func (suite *SlogTestSuite) SetupTest() {
	suite.Buffer = &bytes.Buffer{}
}

// SimpleHandler returns a simple handler to be used in an slog.Logger.
// Override this method to test other types of slog JSON handlers.
// TODO: Can this be moved into simpleLogger()?
func (suite *SlogTestSuite) SimpleHandler() slog.Handler {
	return slog.NewJSONHandler(suite.Buffer, nil)
}

func (suite *SlogTestSuite) simpleLogger() *slog.Logger {
	return slog.New(suite.SimpleHandler())
}

// TestSimpleAttributes tests whether attributes are logged properly.
func (suite *SlogTestSuite) TestSimpleAttributes() {
	logger := suite.simpleLogger()
	logger.Info(message, "first", "one", "second", 2, "pi", math.Pi)
	logMap := suite.logMap()
	suite.assertFieldCount(6, logMap)
	suite.Assert().Equal("one", logMap["first"])
	suite.Assert().Equal(float64(2), logMap["second"])
	suite.Assert().Equal(math.Pi, logMap["pi"])
}

// TestSimpleDuplicateAttributes tests whether duplicate attributes are logged properly.
// Based on the existing behavior of log/slog the second occurrence overrides the first.
func (suite *SlogTestSuite) TestSimpleDuplicateAttributes() {
	logger := suite.simpleLogger()
	logger.Info(message, "alpha", "one", "alpha", 2)
	logMap := suite.logMap()
	suite.Assert().Len(logMap, 4)
	counter := suite.fieldCounter()
	suite.Require().NoError(counter.Parse())
	suite.Assert().Equal(uint(4), counter.NumFields())
	duplicates := counter.Duplicates()
	suite.Assert().Len(duplicates, 1)
	suite.Assert().Equal(uint(2), duplicates["alpha"])
	suite.Assert().Equal(float64(2), logMap["alpha"])
}

// TestNilAttribute tests whether attributes with nil values are logged properly.
// Based on the existing behavior of log/slog the field is created with a nil/null value.
func (suite *SlogTestSuite) TestNilAttribute() {
	logger := suite.simpleLogger()
	logger.Info(message, "first", "one", "second", nil, "pi", math.Pi)
	logMap := suite.logMap()
	suite.assertFieldCount(6, logMap)
	suite.Assert().Equal("one", logMap["first"])
	suite.Assert().Nil(logMap["second"])
	suite.Assert().Equal(math.Pi, logMap["pi"])
}

// TestEmptyAttributeName tests whether attributes with empty names are logged properly.
// Based on the existing behavior of log/slog the field is created with a blank name.
func (suite *SlogTestSuite) TestEmptyAttributeName() {
	logger := suite.simpleLogger()
	logger.Info(message, "first", "one", "", 2, "pi", math.Pi)
	logMap := suite.logMap()
	suite.assertFieldCount(6, logMap)
	suite.Assert().Equal("one", logMap["first"])
	value, found := logMap[""]
	suite.Assert().True(found)
	suite.Assert().Equal(float64(2), value)
	suite.Assert().Equal(math.Pi, logMap["pi"])
}

// TestEmptyAttribute tests whether attributes with empty names and nil values are logged properly.
// Based on the existing behavior of log/slog the field is hot created.
func (suite *SlogTestSuite) TestEmptyAttribute() {
	logger := suite.simpleLogger()
	logger.Info(message, "first", "one", "", nil, "pi", math.Pi)
	logMap := suite.logMap()
	suite.assertFieldCount(5, logMap)
	suite.Assert().Equal("one", logMap["first"])
	_, found := logMap[""]
	suite.Assert().False(found)
	suite.Assert().Equal(math.Pi, logMap["pi"])
}

// TestSimpleDisabled tests whether logging is disabled by level.
func (suite *SlogTestSuite) TestSimpleDisabled() {
	logger := suite.simpleLogger()
	logger.Debug(message)
	suite.Assert().Empty(suite.Buffer)
}

// TestSimpleKeys tests whether the three basic keys are present as their defined constants.
func (suite *SlogTestSuite) TestSimpleKeys() {
	logger := suite.simpleLogger()
	logger.Info(message)
	logMap := suite.logMap()
	suite.assertFieldCount(3, logMap)
	suite.Assert().Equal("INFO", logMap[slog.LevelKey])
	suite.Assert().Equal(message, logMap[slog.MessageKey])
	suite.Assert().NotNil(logMap[slog.TimeKey])
}

// TestSimpleLevel tests whether the simple logger is created with slog.LevelInfo.
// Other tests (e.g. TestSimpleDisabled) depend on this.
func (suite *SlogTestSuite) TestSimpleLevel() {
	logger := suite.simpleLogger()
	suite.Assert().False(logger.Enabled(context.TODO(), -1))
	suite.Assert().True(logger.Enabled(context.TODO(), slog.LevelInfo))
	suite.Assert().True(logger.Enabled(context.TODO(), 1))
	suite.Assert().True(logger.Enabled(context.TODO(), slog.LevelWarn))
	suite.Assert().True(logger.Enabled(context.TODO(), slog.LevelError))
}

// -----------------------------------------------------------------------------

// assertFieldCount checks whether the prescribed number of fields exist at the top level.
// In addition to using the logMap generated by unmarshaling the JSON log data,
// the custom test.FieldCounter is used to make sure there are no duplicates.
func (suite *SlogTestSuite) assertFieldCount(count int, logMap map[string]any) {
	suite.Assert().Len(logMap, count)
	// Double check to make sure there are no duplicate fields at the top level.
	counter := suite.fieldCounter()
	suite.Require().NoError(counter.Parse())
	suite.Assert().Equal(uint(count), counter.NumFields())
	suite.Assert().Empty(counter.Duplicates())
}

// -----------------------------------------------------------------------------

func (suite *SlogTestSuite) fieldCounter() *testJSON.FieldCounter {
	return testJSON.NewFieldCounter(suite.Buffer.Bytes())
}

func (suite *SlogTestSuite) logMap() map[string]any {
	var results map[string]any
	suite.Require().NoError(json.Unmarshal(suite.Buffer.Bytes(), &results))
	return results
}

// -----------------------------------------------------------------------------

func (suite *SlogTestSuite) TestXXX() {
	test.Debugf(0, "Dummy test")
}
