#!/bin/bash

# Run slog benchmark tests.
# Save benchmark output to docs/bench.txt.
# Run cmd/tabular on benchmark output and save results to docs/tabular.txt.

clear
go test -bench=. bench/*.go                    | # Run benchmark tests                \
   tee /dev/tty                                | # Show progress to user in real time \
   tee docs/bench.txt                          | # Save benchmark output              \
   go run cmd/tabular/tabular.go               | # Process JSON to table              \
   tee docs/tabular.txt                          # Save table to file
