#!/bin/bash
# Runs benchmark tests in a specific directory.
# Executes the tests with several different -benchtime settings.

if [ "$1" == "" ] || [ "$2" == "" ]; then
  echo "usage:    comp <dir> <test>"
  echo "               <dir>  directory in which tests are located"
  echo "               <test> is root name of tests, not including initial 'Benchmark'"
  echo "example:  comp handlers/flash Memory"
  exit
fi

clear
echo 1 second
go test -bench=Benchmark$2 -benchtime=1s -benchmem $1/*.go
echo 5 seconds
go test -bench=Benchmark$2 -benchtime=5s -benchmem $1/*.go
echo 15 seconds
go test -bench=Benchmark$2 -benchtime=15s -benchmem $1/*.go
echo 60 seconds
go test -bench=Benchmark$2 -benchtime=60s -benchmem $1/*.go
echo Done
