#!/bin/bash

# Run slog verification tests.
# Save verification output to docs/verify.txt.

clear
go test -v ./verify                    | # Run verification tests  \
   tee docs/verify.txt                   # Save benchmark output
