// Package docs contains cmd/server pages generated by GitHub [Actions]
// and served by GitHub [Pages].
//
// [Actions]: https://docs.github.com/en/actions
// [Pages]: https://docs.github.com/en/pages
package docs
