// Package docs contains cmd/server pages generated by [GitHub Actions]
// and served by [GitHub Pages].
//
// [GitHub Actions]: https://docs.github.com/en/actions
// [GitHub Pages]: https://docs.github.com/en/pages
package docs
