name: Update benchmark pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - server-pages

jobs:
  run_benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install the latest versions of each library
        run: go get -u ./... && go mod tidy

      - name: Benchmark Go Logging Libraries
        run: go test -bench=. bench/*.go > /tmp/bench.txt

#      - name: Commit benchmark results to repo
#        uses: EndBug/add-and-commit@v9
#        with:
#          message: Update benchmark results
#          commit: '--no-verify'
