name: Update benchmark pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  run_benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install the latest versions of each library
        run: go get -u ./... && go mod tidy

      - name: Remove previous documentation pages (except for doc.go)
        run: |
          rm -rf docs/*
          git checkout docs/doc.go

      - name: Benchmark Go logging libraries
        run: go test -bench=. bench/*.go > docs/bench.txt

      - name: Verify Go logging libraries
        run: go test -v ./verify > docs/verify.txt

      - name: Run Tabular
        run: go run cmd/tabular/tabular.go -bench=docs/bench.txt -verify=docs/verify.txt > docs/tabular.txt

      - name: Run Server & Get Pages
        run: go run cmd/server/*.go -bench=docs/bench.txt -verify=docs/verify.txt & scripts/pages

      - name: Commit Benchmark Results to Repo
        uses: EndBug/add-and-commit@v9
        with:
          message: Update Benchmark Results
          commit: '--no-verify'
